a2lix_translation_form:
    locale_provider: default       # [1]
    locales: [en, fr, es, de]      # [1-a]
    default_locale: fr             # [1-b]
    required_locales: [fr]         # [1-c]
    templating: "default.html.twig"      # [2]