vich_uploader:
    db_driver: orm

    mappings:
        test_images:
            uri_prefix: '%app.path.test_images%'
            upload_destination: '%kernel.project_dir%/public/uploads/images/test_images'
